[build-system]
requires = [
    "setuptools",
    "wheel",
    # provides the oldest numpy version with wheels on PyPI
    "oldest-supported-numpy",
    "Cython~=0.29.36",
]

[tool.ruff]
line-length=119

[tool.ruff.lint]
select = [
    "F",
    "I",
    "E",
    "W",
    "UP",
    "NPY",
]
