name: docs
channels:
=  - conda-forge
dependencies:
  # Base depends
  - pip
  - python=3.11

  # other libraries
  - pip
  - setuptools
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  - nbsphinx_link
  - msmb_theme
  - pandoc
 
  # python libraries
  - jupyter
  - ipython
  - matplotlib
  - jinja2
  - runipy
  - openmm
  - scikit-learn
  - pytest
  - pandas
  - numpydoc
  - wheel
  - tables