name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        include:
         - py: "python37"
           nixpkgs: "channel:nixos-20.09"
         - py: "python38"
           nixpkgs: "https://github.com/NixOS/nixpkgs/archive/54c1e44240d8a527a8f4892608c4bce5440c3ecb.tar.gz"
         #- py: "python39"
         #  nixpkgs: "https://github.com/NixOS/nixpkgs/archive/54c1e44240d8a527a8f4892608c4bce5440c3ecb.tar.gz"

    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=${{ matrix.nixpkgs }}
    - uses: cachix/cachix-action@v8
      with:
        name: nixpkgs-review-bot
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build
      run: nix-build -E "with import <nixpkgs> {}; $PYTHON.pkgs.callPackage ./. {}"
      env:
        PYTHON: ${{ matrix.py }}
    - uses: actions/upload-artifact@v2
      with:
        name: docs-${{ matrix.py }}
        path: result/share/docs

  Deploy:
    needs: [ Build ]
    runs-on: ubuntu-20.04
    steps:
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: channel:nixos-20.09
    - uses: actions/download-artifact@v2
      with:
        name: docs-python37
    - run: |
        nix-env -f '<nixpkgs>' -iA awscli2

        echo "<html><head><meta http-equiv=\"refresh\" content=\"0; url=./$VERSION\"></head></html>" > index.html

        aws s3 sync html s3://mdtraj/$VERSION
        aws s3 cp index.html s3://mdtraj
      env:
        VERSION: "1.9.5"
        AWS_DEFAULT_REGION: us-east-1
        AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
